language: shell
sudo: required

services:
- docker

arch:
  packages:
    - openssh
    - subversion
    - rsync
    - arch-install-scripts
    - git
    - bzr
    - mercurial
    - diffutils
    - asciidoc
    - shellcheck
  script:
    - sudo pacman -Syu --noconfirm --needed "${CONFIG_PACKAGES[@]}"
    - make PREFIX=/usr
    - make PREFIX=/usr DESTDIR="$(mktemp -d)" install
    - make check || true
    - SHELLCHECK_OPTS="-S error" make check

script: 'curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash'

# vim: ft=yaml ts=2 sw=2 et:
